#AND (PARA QUE NOS DEVUELVA TRUE LAS DOS CONDICIONES TIENEN QUE SER VERDADERAS, SINO DEVUELVE FALSE)


#OR (NOS DEVUELVE FALSO SOLAMENTE SI NINGUNA SE CUMPLE)



#NOT (NEGACION, SI LE DAMOS TRUE DEVUELVE FALSO, Y VICEVERSA)